version: "3.7"
services:
    db:
        image: postgres:13.2-alpine
        restart: always
        environment:
            POSTGRES_DB: privatenet
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "15432:5432"
    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: test@email.com
            PGADMIN_DEFAULT_PASSWORD: 1234
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "15600:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "db:pgsql-server"

volumes:
    db-data:
    pgadmin-data: